version: '3.7'

services:

  sqlsocialmedia:
    build: ./sql
    ports:
      - 1433:1433
    networks:
      - socialMediaNAT
    
  apisocialmedia:
    build: ./SocialMedia
    ports:
      - 5000:5000
    networks: 
      - socialMediaNAT
    depends_on: 
      - sqlsocialmedia
    
networks:
  socialMediaNAT: